/* Live Ventures — employee master.
   Update this file when someone joins or leaves; nothing else needs to change.
   Fields: id, name, designation, department, joined (ISO yyyy-mm-dd, "" if unknown) */
window.EMPLOYEES = [
  {id:"LE-DHK-1001", name:"Fahad Kawsar", designation:"Founder & Chairman", department:"Office of the Founders", joined:""},
  {id:"LE-DHK-1002", name:"Gazi Nashek Rabbani", designation:"Co-Founder & COO", department:"Operations", joined:""},
  {id:"LE-DHK-1003", name:"Shefat A. Khan", designation:"Co-Founder & CIO", department:"Infrastructure", joined:""},
  {id:"LE-DHK-1004", name:"Farhana Zaman", designation:"Head", department:"Product Development", joined:""},
  {id:"LE-DHK-1005", name:"Palash Sutradhar", designation:"Manager", department:"Supply Chain & Procurement", joined:"2026-01-19"},
  {id:"LE-DHK-1006", name:"Shafin Ahmed Nihal", designation:"Partners' Secretary", department:"Office of the Founders", joined:"2026-05-01"},
  {id:"LE-DHK-1007", name:"Mahmudul Hasan Sumon", designation:"IT Coordinator", department:"Technology", joined:"2026-02-08"},
  {id:"LE-DHK-1008", name:"Delwer Hussain Raju", designation:"Executive", department:"Supply Chain & Procurement", joined:"2026-02-08"},
  {id:"LE-DHK-1009", name:"Md. Romiz Raza", designation:"Executive", department:"Supply Chain & Procurement", joined:"2026-02-22"},
  {id:"LE-DHK-1010", name:"Md. Mahadi Hasan", designation:"Real Estate Associate", department:"Real Estate", joined:"2026-02-08"},
  {id:"LE-DHK-1011", name:"Nachim Ahamed", designation:"General Manager", department:"Operations", joined:"2026-03-01"},
  {id:"LE-DHK-1012", name:"Oahidul Islam", designation:"Office Staff", department:"Admin", joined:"2026-02-01"},
  {id:"LE-DHK-1013", name:"Sanjida Akhi Khushmoti", designation:"Trainee Executive", department:"Admin", joined:"2026-04-01"},
  {id:"LE-DHK-1014", name:"Ahnaf Akif", designation:"DGM & Head", department:"Marketing & Communications", joined:"2026-04-12"},
  {id:"LE-DHK-1015", name:"Dewan Fayaz Been Faruque", designation:"Senior Manager", department:"Marketing & Communications", joined:"2026-04-19"},
  {id:"LE-DHK-1016", name:"Md. Nuruzzaman Khan", designation:"Development Executive", department:"Sales", joined:"2026-04-05"},
  {id:"LE-DHK-1017", name:"Peu Das Dewan", designation:"Senior Executive", department:"Accounts & Finance", joined:"2026-04-07"},
  {id:"LE-DHK-1018", name:"H. M. Mahfujur Rahman", designation:"Head of Sales", department:"Sales", joined:"2026-05-03"},
  {id:"LE-DHK-1019", name:"Md. Rakibul Islam", designation:"Senior Manager, Strategy & Planning", department:"Marketing & Communications", joined:"2026-06-13"},
  {id:"LE-DHK-1020", name:"Ahmad Mustafa Zehadi (Nosib)", designation:"Creative Director", department:"Marketing & Communications", joined:"2026-06-14"},
  {id:"LE-DHK-1021", name:"Bedhan Chandra Ray", designation:"Senior Executive, Creative", department:"Marketing & Communications", joined:"2026-06-21"},
  {id:"LE-DHK-1022", name:"Yasin Arafat Antu", designation:"Junior Architect", department:"Infrastructure", joined:"2026-06-25"},
  {id:"LE-DHK-1023", name:"Md. Shahed Chowdhury", designation:"Head", department:"Accounts & Finance", joined:"2026-08-23"},
  {id:"LE-DHK-1024", name:"Rifat Bin Alam Rohit", designation:"Product Consultant", department:"Technology", joined:"2026-05-01"},
  {id:"LE-DHK-1025", name:"Dominic Gomes", designation:"Head Chef", department:"Product Development", joined:"2026-04-01"},
  {id:"LE-DHK-1026", name:"Ahsanul Hoque", designation:"Tech Consultant", department:"Technology", joined:"2026-06-18"},
  {id:"LE-DHK-1027", name:"Md. Golap Hossen", designation:"Infrastructure Assistant", department:"Civil", joined:"2026-03-09"},
  {id:"LE-DHK-1028", name:"Md. Mehedi Hasan", designation:"Office Staff", department:"Admin", joined:"2026-03-25"},
  {id:"LE-DHK-1029", name:"Md. Mirajul Islam", designation:"Office Staff (Dimond Shine Cleaning Service)", department:"Admin", joined:"2026-04-16"},
  {id:"LE-DHK-1030", name:"Pinky Monalisa", designation:"Intern", department:"Supply Chain & Procurement", joined:"2026-07-19"},
  {id:"LE-DHK-1031", name:"Subash James D'Rozario", designation:"Japanese, Pan Asian & Malay Chef", department:"Product Development", joined:"2026-05-12"},
  {id:"LE-DHK-1032", name:"Paul Gomez", designation:"Continental Cuisine, Grill & Saucier Chef", department:"Product Development", joined:"2026-05-12"},
  {id:"LE-DHK-1033", name:"Roxy Gomes", designation:"Demi Chef de Partie (Asian Food & Sushi)", department:"Product Development", joined:"2026-05-12"},
  {id:"LE-DHK-1034", name:"Md. Ridoy Ahmed", designation:"Snacks, Drinks, Indian & Arabian Chef", department:"Product Development", joined:"2026-05-12"},
  {id:"LE-DHK-1035", name:"Polash D Costa", designation:"Demi Chef de Partie (Continental, Grill & Steak)", department:"Product Development", joined:"2026-05-12"},
  {id:"LE-DHK-1038", name:"Md. Sumon Mia", designation:"Chef de Partie — Bangla Kitchen", department:"Product Development", joined:"2026-07-07"},
  {id:"LE-DHK-1039", name:"Mathius Prakash Gomes", designation:"Demi Chef de Partie (Arabic, Continental, Grill & Cold Kitchen)", department:"Product Development", joined:"2026-05-17"},
  {id:"LE-DHK-1040", name:"Shubir Gomes", designation:"Demi Chef de Partie (Continental)", department:"Product Development", joined:"2026-05-12"},
  {id:"LE-DHK-1042", name:"Diponkor Costa", designation:"Chef de Partie", department:"Product Development", joined:"2026-07-07"},
  {id:"LE-DHK-1043", name:"Morina Gomes", designation:"Chef de Partie — Bangla Kitchen", department:"Product Development", joined:"2026-07-07"},
  {id:"LE-DHK-1044", name:"Md. Imran Dhaly Linkon", designation:"Demi Chef de Partie — Bangla Kitchen", department:"Product Development", joined:"2026-07-07"},
  {id:"LE-DHK-1045", name:"Dominic Richard Gomes", designation:"Demi Chef de Partie — Bangla Kitchen", department:"Product Development", joined:"2026-07-07"},
  {id:"LE-DHK-1046", name:"Rahul James Gomes", designation:"Assistant Cook — Bangla Kitchen", department:"Product Development", joined:"2026-07-07"},
  {id:"LE-DHK-1048", name:"Desmond Ashish Rodrick", designation:"Commis I / Kitchen Assistant", department:"Product Development", joined:"2026-07-07"},
  {id:"LE-DHK-1049", name:"Bishal Anthony Prodhan", designation:"Steward", department:"Product Development", joined:"2026-07-07"},
  {id:"LE-DHK-1050", name:"Ovi Sarkar", designation:"Steward", department:"Product Development", joined:"2026-07-07"},
  {id:"LE-DHK-1051", name:"Md. Abdur Rahman Roni", designation:"Warehouse Assistant", department:"Operations", joined:"2026-07-15"},
  {id:"LE-DHK-1052", name:"Seefat Ahmed", designation:"Outlet Manager", department:"Restaurant Operations", joined:"2026-08-01"},
  {id:"LE-DHK-1053", name:"Saad Abdullah Shezan", designation:"Manager", department:"Customer Experience", joined:"2026-08-02"},
  {id:"LE-DHK-1054", name:"Imtiaz Mahboob", designation:"Project Manager", department:"Technology", joined:"2026-08-02"}
];
